default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: allmyfishing_development


test:
  <<: *default
  database: allmyfishing_test

production:
  <<: *default
  database: allmyfishing_production
  username: allmyfishing
  password: <%= ENV["ALLMYFISHING_DATABASE_PASSWORD"] %>
